### ISSUE TITLE
使用image.pick出现错误undefined is not an object (evaluating '_natjs2.default.image.pick'

### ISSUE THREAD

**Issue by CTOSPACE** [Natjs/weex-nat-media-image#1]
使用image.pick的时候出现错误，undefined is not an object (evaluating '_natjs2.default.image.pick'。
插件也安装了，natjs也安装了。然后下面的代码就会在出现错误，这个是什么原因，一直找不到问题。
`Nat.image.pick((err, ret) => {
          modal.alert({message: JSON.stringify(ret)});
        })`

错误信息如下：
![tim 20170702090540](https://user-images.githubusercontent.com/1892162/27766553-6418238a-5f06-11e7-9f9b-a7ca44db1ee2.png)

**Comment by acathur** [comment]
bug fixed
