### ISSUE TITLE
pick image and instantly use your paths in image tag on app body

### ISSUE THREAD

**Issue by TecladistaProd** [Natjs/weex-nat-media-image#2]
i tried use this,
`
Nat.image.pick({
            limit: 1,
            showCamera: true
        }, function (err, ret) {
            this.myImage = ret.paths
        })
`
but in android give render error, what's wrong ?

**Comment by TecladistaProd** [comment]
i will try use `this.image = ret.paths[0]`, if i have success i return and close this.

**Comment by acathur** [comment]
Could you please provide error logs?

**Comment by TecladistaProd** [comment]
![whatsapp image 2017-08-19 at 17 33 07](https://user-images.githubusercontent.com/26743405/29490140-e46d563a-8509-11e7-8050-d99c7d1da06c.jpeg)

**Comment by acathur** [comment]
Please provide error logs in console (Android Studio)

**Comment by TecladistaProd** [comment]
` npm install&build
npm WARN xxx@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ios-deploy@1.9.1 (node_modules\ios-deploy):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for ios-deploy@1.9.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})


> xxx@1.0.0 build C:\Users\Vitor Tecladista\Documents\Vue JS\weex\app
> webpack

Hash: 2672dc798d1e83a8457cfaa239011f9a70dfdc4c
Version: webpack 2.7.0
Child
    Hash: 2672dc798d1e83a8457c
    Time: 5445ms
           Asset     Size  Chunks             Chunk Names
    index.web.js  29.7 kB       0  [emitted]  index
       [0] ./src/index.vue 1.48 kB {0} [built]
       [1] ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/index.vue 1.08 kB {0} [built]
       [2] ./temp?entry=true 72 bytes {0} [built]
       [3] ./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-36a6675b!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/index.vue 681 bytes {0} [built]
       [4] ./~/css-loader/lib/css-base.js 1.46 kB {0} [built]
       [5] ./~/natjs/lib/camera/index.js 1.41 kB {0} [built]
       [6] ./~/natjs/lib/communication/index.js 2.89 kB {0} [built]
      [14] ./~/natjs/lib/geolocation/index.js 1.7 kB {0} [built]
      [15] ./~/natjs/lib/index.js 1.67 kB {0} [built]
      [25] ./~/natjs/lib/recorder/index.js 1.74 kB {0} [built]
      [28] ./~/natjs/lib/sensor/index.js 404 bytes {0} [built]
      [30] ./~/vue-loader/lib/component-normalizer.js 1.12 kB {0} [built]
      [31] ./~/vue-loader/lib/template-compiler.js?id=data-v-36a6675b!./~/vue-loader/lib/selector.js?type=template&index=0!./src/index.vue 1.08 kB {0} [built]
      [32] ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-36a6675b!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/index.vue 1.33 kB {0} [built]
      [33] ./~/vue-style-loader/lib/addStylesClient.js 6.05 kB {0} [built]
        + 20 hidden modules
Child
    Hash: faa239011f9a70dfdc4c
    Time: 4700ms
       Asset     Size  Chunks             Chunk Names
    index.js  26.2 kB       0  [emitted]  index
       [0] ./~/weex-vue-loader/lib/script-loader.js!./~/babel-loader/lib!./~/weex-vue-loader/lib/selector.js?type=script&index=0!./src/index.vue 1.08 kB {0} [built]
       [1] ./~/weex-vue-loader/lib/style-loader.js!./~/weex-vue-loader/lib/style-rewriter.js?id=data-v-2a1cfdc8!./~/weex-vue-loader/lib/selector.js?type=styles&index=0!./src/index.vue 560 bytes {0} [built]
       [2] ./~/weex-vue-loader/lib/template-compiler.js?id=data-v-2a1cfdc8!./~/weex-vue-loader/lib/selector.js?type=template&index=0!./src/index.vue 885 bytes {0} [built]
       [3] ./~/natjs/lib/camera/index.js 1.41 kB {0} [built]
       [4] ./~/natjs/lib/communication/index.js 2.89 kB {0} [built]
       [6] ./~/natjs/lib/device/index.js 822 bytes {0} [built]
      [12] ./~/natjs/lib/geolocation/index.js 1.7 kB {0} [built]
      [13] ./~/natjs/lib/index.js 1.67 kB {0} [built]
      [16] ./~/natjs/lib/media/index.js 450 bytes {0} [built]
      [18] ./~/natjs/lib/modal/index.js 2.89 kB {0} [built]
      [19] ./~/natjs/lib/navigator/index.js 4.26 kB {0} [built]
      [20] ./~/natjs/lib/network/index.js 461 bytes {0} [built]
      [23] ./~/natjs/lib/recorder/index.js 1.74 kB {0} [built]
      [26] ./~/natjs/lib/sensor/index.js 404 bytes {0} [built]
      [28] ./src/index.vue?entry=true 1.73 kB {0} [built]
        + 14 hidden modules

 => Will start Android app
============build config============
AppId=>com.TecladistaProd.alibaba.weex
AppName=>VitorApp
SplashText=>Bem Vindo
Vitor
WeexBundle=>index.js
if you want to change build config.please modify android.config.json
Android Debug Bridge version 1.0.31

 -d                            - directs command to the only connected USB device
                                 returns an error if more than one USB device is present.
 -e                            - directs command to the only running emulator.
                                 returns an error if more than one emulator is running.
 -s <specific device>          - directs command to the device or emulator with the given
                                 serial number or qualifier. Overrides ANDROID_SERIAL
                                 environment variable.
 -p <product name or path>     - simple product name like 'sooner', or
                                 a relative/absolute path to a product
                                 out directory like 'out/target/product/sooner'.
                                 If -p is not specified, the ANDROID_PRODUCT_OUT
                                 environment variable is used, which must
                                 be an absolute path.
 devices [-l]                  - list all connected devices
                                 ('-l' will also list device qualifiers)
 connect <host>[:<port>]       - connect to a device via TCP/IP
                                 Port 5555 is used by default if no port number is specified.  disconnect [<host>[:<port>]]  - disconnect from a TCP/IP device.
                                 Port 5555 is used by default if no port number is specified.
                                 Using this command with no additional arguments
                                 will disconnect from all connected TCP/IP devices.

device commands:
  adb push <local> <remote>    - copy file/dir to device
  adb pull <remote> [<local>]  - copy file/dir from device
  adb sync [ <directory> ]     - copy host->device only if changed
                                 (-l means list but don't copy)
                                 (see 'adb help all')
  adb shell                    - run remote shell interactively
  adb shell <command>          - run remote shell command
  adb emu <command>            - run emulator console command
  adb logcat [ <filter-spec> ] - View device log
  adb forward <local> <remote> - forward socket connections
                                 forward specs are one of:
                                   tcp:<port>
                                   localabstract:<unix domain socket name>
                                   localreserved:<unix domain socket name>
                                   localfilesystem:<unix domain socket name>
                                   dev:<character device name>
                                   jdwp:<process pid> (remote only)
  adb jdwp                     - list PIDs of processes hosting a JDWP transport
  adb install [-l] [-r] [-s] [--algo <algorithm name> --key <hex-encoded key> --iv <hex-encoded iv>] <file>
                               - push this package file to the device and install it
                                 ('-l' means forward-lock the app)
                                 ('-r' means reinstall the app, keeping its data)
                                 ('-s' means install on SD card instead of internal storage)
                                 ('--algo', '--key', and '--iv' mean the file is encrypted already)
  adb uninstall [-k] <package> - remove this app package from the device
                                 ('-k' means keep the data and cache directories)
  adb bugreport                - return all information from the device
                                 that should be included in a bug report.

  adb backup [-f <file>] [-apk|-noapk] [-shared|-noshared] [-all] [-system|-nosystem] [<packages...>]
                               - write an archive of the device's data to <file>.
                                 If no -f option is supplied then the data is written
                                 to "backup.ab" in the current directory.
                                 (-apk|-noapk enable/disable backup of the .apks themselves
                                    in the archive; the default is noapk.)
                                 (-shared|-noshared enable/disable backup of the device's
                                    shared storage / SD card contents; the default is noshared.)
                                 (-all means to back up all installed applications)
                                 (-system|-nosystem toggles whether -all automatically includes
                                    system applications; the default is to include system apps)
                                 (<packages...> is the list of applications to be backed up.
If
                                    the -all or -shared flags are passed, then the package
                                    list is optional.  Applications explicitly given on the
                                    command line will be included even if -nosystem would
                                    ordinarily cause them to be omitted.)

  adb restore <file>           - restore device contents from the <file> backup archive

  adb help                     - show this help message
  adb version                  - show version num

scripting:
  adb wait-for-device          - block until device is online
  adb start-server             - ensure that there is a server running
  adb kill-server              - kill the server if it is running
  adb get-state                - prints: offline | bootloader | device
  adb get-serialno             - prints: <serial-number>
  adb get-devpath              - prints: <device-path>
  adb status-window            - continuously print device status for a specified device
  adb remount                  - remounts the /system partition on the device read-write
  adb reboot [bootloader|recovery] - reboots the device, optionally into the bootloader or recovery program
  adb reboot-bootloader        - reboots the device into the bootloader
  adb root                     - restarts the adbd daemon with root permissions
  adb usb                      - restarts the adbd daemon listening on USB
  adb tcpip <port>             - restarts the adbd daemon listening on TCP on the specified port
networking:
  adb ppp <tty> [parameters]   - Run PPP over USB.
 Note: you should not automatically start a PPP connection.
 <tty> refers to the tty for PPP stream. Eg. dev:/dev/omap_csmi_tty1
 [parameters] - Eg. defaultroute debug dump local notty usepeerdns

adb sync notes: adb sync [ <directory> ]
  <localdir> can be interpreted in several ways:

  - If <directory> is not specified, both /system and /data partitions will be updated.

  - If it is "system" or "data", only the corresponding partition
    is updated.

environmental variables:
  ADB_TRACE                    - Print debug information. A comma separated list of the following values
                                 1 or all, adb, sockets, packets, rwx, usb, sync, sysdeps, transport, jdwp
  ANDROID_SERIAL               - The serial number to connect to. -s takes priority over this if given.
  ANDROID_LOG_TAGS             - When used with the logcat option, only these debug tags are printed.
reverse error[ignored]
 => Building app ...
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:appframework:preBuild UP-TO-DATE
:appframework:preReleaseBuild UP-TO-DATE
:appframework:checkReleaseManifest
:appframework:preDebugAndroidTestBuild UP-TO-DATE
:appframework:preDebugBuild UP-TO-DATE
:appframework:preDebugUnitTestBuild UP-TO-DATE
:appframework:preReleaseUnitTestBuild UP-TO-DATE
:appframework:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:appframework:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:appframework:prepareComFacebookFrescoDrawee0100Library UP-TO-DATE
:appframework:prepareComFacebookFrescoFbcore0100Library UP-TO-DATE
:appframework:prepareComFacebookFrescoFresco0100Library UP-TO-DATE
:appframework:prepareComFacebookFrescoImagepipeline0100Library UP-TO-DATE
:appframework:prepareComFacebookFrescoImagepipelineBase0100Library UP-TO-DATE
:appframework:prepareComTaobaoAndroidWeex_sdk0100Library UP-TO-DATE
:appframework:prepareReleaseDependencies
:appframework:compileReleaseAidl UP-TO-DATE
:appframework:compileReleaseNdk UP-TO-DATE
:appframework:compileLint UP-TO-DATE
:appframework:copyReleaseLint UP-TO-DATE
:appframework:compileReleaseRenderscript UP-TO-DATE
:appframework:generateReleaseBuildConfig UP-TO-DATE
:appframework:generateReleaseResValues UP-TO-DATE
:appframework:generateReleaseResources UP-TO-DATE
:appframework:mergeReleaseResources UP-TO-DATE
:appframework:processReleaseManifest UP-TO-DATE
:appframework:processReleaseResources UP-TO-DATE
:appframework:generateReleaseSources UP-TO-DATE
:appframework:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:appframework:compileReleaseJavaWithJavac UP-TO-DATE
:appframework:extractReleaseAnnotations UP-TO-DATE
:appframework:mergeReleaseShaders UP-TO-DATE
:appframework:compileReleaseShaders UP-TO-DATE
:appframework:generateReleaseAssets UP-TO-DATE
:appframework:mergeReleaseAssets UP-TO-DATE
:appframework:mergeReleaseProguardFiles UP-TO-DATE
:appframework:packageReleaseRenderscript UP-TO-DATE
:appframework:packageReleaseResources UP-TO-DATE
:appframework:processReleaseJavaRes UP-TO-DATE
:appframework:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:appframework:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:appframework:mergeReleaseJniLibFolders UP-TO-DATE
:appframework:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:appframework:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:appframework:bundleRelease UP-TO-DATE
:weexplugin:preBuild UP-TO-DATE
:weexplugin:preReleaseBuild UP-TO-DATE
:weexplugin:checkReleaseManifest
:weexplugin:preDebugAndroidTestBuild UP-TO-DATE
:weexplugin:preDebugBuild UP-TO-DATE
:weexplugin:preDebugUnitTestBuild UP-TO-DATE
:weexplugin:preReleaseUnitTestBuild UP-TO-DATE
:weexplugin:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:weexplugin:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:weexplugin:prepareComNatGeolocation103Library UP-TO-DATE
:weexplugin:prepareComNatMediaImage111Library UP-TO-DATE
:weexplugin:prepareComNatModal105Library UP-TO-DATE
:weexplugin:prepareComNatPermission102Library UP-TO-DATE
:weexplugin:prepareComTaobaoAndroidWeex_sdk0100Library UP-TO-DATE
:weexplugin:prepareReleaseDependencies
:weexplugin:compileReleaseAidl UP-TO-DATE
:weexplugin:compileReleaseNdk UP-TO-DATE
:weexplugin:compileLint UP-TO-DATE
:weexplugin:copyReleaseLint UP-TO-DATE
:weexplugin:compileReleaseRenderscript UP-TO-DATE
:weexplugin:generateReleaseBuildConfig UP-TO-DATE
:weexplugin:generateReleaseResValues UP-TO-DATE
:weexplugin:generateReleaseResources UP-TO-DATE
:weexplugin:mergeReleaseResources UP-TO-DATE
:weexplugin:processReleaseManifest UP-TO-DATE
:weexplugin:processReleaseResources UP-TO-DATE
:weexplugin:generateReleaseSources UP-TO-DATE
:weexplugin:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:weexplugin:compileReleaseJavaWithJavac UP-TO-DATE
:weexplugin:extractReleaseAnnotations UP-TO-DATE
:weexplugin:mergeReleaseShaders UP-TO-DATE
:weexplugin:compileReleaseShaders UP-TO-DATE
:weexplugin:generateReleaseAssets UP-TO-DATE
:weexplugin:mergeReleaseAssets UP-TO-DATE
:weexplugin:mergeReleaseProguardFiles UP-TO-DATE
:weexplugin:packageReleaseRenderscript UP-TO-DATE
:weexplugin:packageReleaseResources UP-TO-DATE
:weexplugin:processReleaseJavaRes UP-TO-DATE
:weexplugin:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:weexplugin:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:weexplugin:mergeReleaseJniLibFolders UP-TO-DATE
:weexplugin:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:weexplugin:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:weexplugin:bundleRelease UP-TO-DATE
:app:prepareAndroidAppframeworkUnspecifiedLibrary UP-TO-DATE
:app:prepareAndroidWeexpluginUnspecifiedLibrary UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:app:prepareComAndroidSupportDesign2311Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72311Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee0100Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore0100Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco0100Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline0100Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineBase0100Library UP-TO-DATE
:app:prepareComJourneyappsZxingAndroidEmbedded340Library UP-TO-DATE
:app:prepareComNatGeolocation103Library UP-TO-DATE
:app:prepareComNatMediaImage111Library UP-TO-DATE
:app:prepareComNatModal105Library UP-TO-DATE
:app:prepareComNatPermission102Library UP-TO-DATE
:app:prepareComTaobaoAndroidWeex_inspector01005Library UP-TO-DATE
:app:prepareComTaobaoAndroidWeex_sdk0100Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets
:app:unzipJacocoAgent UP-TO-DATE
:app:transformClassesWithJacocoForDebug UP-TO-DATE
:app:transformClassesWithDexForDebug UP-TO-DATE
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:app:validateSigningDebug
:app:packageDebug
:app:assembleDebug
:app:checkReleaseManifest
:app:prepareReleaseDependencies
:app:compileReleaseAidl UP-TO-DATE
:app:compileReleaseRenderscript UP-TO-DATE
:app:generateReleaseBuildConfig UP-TO-DATE
:app:generateReleaseResValues UP-TO-DATE
:app:generateReleaseResources UP-TO-DATE
:app:mergeReleaseResources UP-TO-DATE
:app:processReleaseManifest UP-TO-DATE
:app:processReleaseResources UP-TO-DATE
:app:generateReleaseSources UP-TO-DATE
:app:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:app:compileReleaseJavaWithJavac UP-TO-DATE
:app:compileReleaseNdk UP-TO-DATE
:app:compileReleaseSources UP-TO-DATE
:app:lintVitalRelease
C:\Users\Vitor Tecladista\Documents\Vue JS\weex\app\platforms\android\app\src\main\res\values\strings.xml:3: Error: "dummy_content" is not translated in "zh-CN" (Chinese: China) [MissingTranslation]
    <string name="dummy_content">Bem Vindo
            ~~~~~~~~~~~~~~~~~~~~
C:\Users\Vitor Tecladista\Documents\Vue JS\weex\app\platforms\android\app\src\main\res\values\strings.xml:9: Error: "index_tip" is not translated in "zh-CN" (Chinese: China) [MissingTranslation]
    <string name="index_tip">Network Error!\n1.Make sure you use the command "npm run serve"
            ~~~~~~~~~~~~~~~~
C:\Users\Vitor Tecladista\Documents\Vue JS\weex\app\platforms\android\app\src\main\res\values\strings.xml:13: Error: "scan_qr_code" is not translated in "zh-CN" (Chinese: China) [MissingTranslation]
    <string name="scan_qr_code">??</string>
            ~~~~~~~~~~~~~~~~~~~
C:\Users\Vitor Tecladista\Documents\Vue JS\weex\app\platforms\android\app\src\main\res\values\strings.xml:14: Error: "page_refresh" is not translated in "zh-CN" (Chinese: China) [MissingTranslation]
    <string name="page_refresh">??</string>
            ~~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "MissingTranslation":
   If an application has more than one locale, then all the strings declared
   in one language should also be translated in all other languages.

   If the string should not be translated, you can add the attribute
   translatable="false" on the <string> element, or you can define all your
   non-translatable strings in a resource file called donottranslate.xml. Or,
   you can ignore the issue with a tools:ignore="MissingTranslation"
   attribute.

   By default this detector allows regions of a language to just provide a
   subset of the strings and fall back to the standard language strings. You
   can require all regions to provide a full translation by setting the
   environment variable ANDROID_LINT_COMPLETE_REGIONS.

   You can tell lint (and other tools) which language is the default language
   in your res/values/ folder by specifying tools:locale="languageCode" for
   the root <resources> element in your resource file. (The tools prefix
   refers to the namespace declaration http://schemas.android.com/tools.)

4 errors, 0 warnings
                                                                                             :app:mergeReleaseShaders UP-TO-DATEease
:app:compileReleaseShaders UP-TO-DATE
:app:generateReleaseAssets UP-TO-DATE
:app:mergeReleaseAssets
:app:transformClassesWithDexForRelease UP-TO-DATE
:app:mergeReleaseJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:app:processReleaseJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:app:packageRelease
:app:assembleRelease
:app:assemble
:appframework:checkDebugManifest
:appframework:prepareDebugDependencies
:appframework:compileDebugAidl UP-TO-DATE
:appframework:compileDebugNdk UP-TO-DATE
:appframework:copyDebugLint UP-TO-DATE
:appframework:compileDebugRenderscript UP-TO-DATE
:appframework:generateDebugBuildConfig UP-TO-DATE
:appframework:generateDebugResValues UP-TO-DATE
:appframework:generateDebugResources UP-TO-DATE
:appframework:mergeDebugResources UP-TO-DATE
:appframework:processDebugManifest UP-TO-DATE
:appframework:processDebugResources UP-TO-DATE
:appframework:generateDebugSources UP-TO-DATE
:appframework:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:appframework:compileDebugJavaWithJavac UP-TO-DATE
:appframework:extractDebugAnnotations UP-TO-DATE
:appframework:mergeDebugShaders UP-TO-DATE
:appframework:compileDebugShaders UP-TO-DATE
:appframework:generateDebugAssets UP-TO-DATE
:appframework:mergeDebugAssets UP-TO-DATE
:appframework:mergeDebugProguardFiles UP-TO-DATE
:appframework:packageDebugRenderscript UP-TO-DATE
:appframework:packageDebugResources UP-TO-DATE
:appframework:processDebugJavaRes UP-TO-DATE
:appframework:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:appframework:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
:appframework:mergeDebugJniLibFolders UP-TO-DATE
:appframework:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:appframework:transformNative_libsWithSyncJniLibsForDebug UP-TO-DATE
:appframework:bundleDebug UP-TO-DATE
:appframework:compileDebugSources UP-TO-DATE
:appframework:assembleDebug UP-TO-DATE
:appframework:compileReleaseSources UP-TO-DATE
:appframework:assembleRelease UP-TO-DATE
:appframework:assemble UP-TO-DATE
:weexplugin:checkDebugManifest
:weexplugin:prepareDebugDependencies
:weexplugin:compileDebugAidl UP-TO-DATE
:weexplugin:compileDebugNdk UP-TO-DATE
:weexplugin:copyDebugLint UP-TO-DATE
:weexplugin:compileDebugRenderscript UP-TO-DATE
:weexplugin:generateDebugBuildConfig UP-TO-DATE
:weexplugin:generateDebugResValues UP-TO-DATE
:weexplugin:generateDebugResources UP-TO-DATE
:weexplugin:mergeDebugResources UP-TO-DATE
:weexplugin:processDebugManifest UP-TO-DATE
:weexplugin:processDebugResources UP-TO-DATE
:weexplugin:generateDebugSources UP-TO-DATE
:weexplugin:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:weexplugin:compileDebugJavaWithJavac UP-TO-DATE
:weexplugin:extractDebugAnnotations UP-TO-DATE
:weexplugin:mergeDebugShaders UP-TO-DATE
:weexplugin:compileDebugShaders UP-TO-DATE
:weexplugin:generateDebugAssets UP-TO-DATE
:weexplugin:mergeDebugAssets UP-TO-DATE
:weexplugin:mergeDebugProguardFiles UP-TO-DATE
:weexplugin:packageDebugRenderscript UP-TO-DATE
:weexplugin:packageDebugResources UP-TO-DATE
:weexplugin:processDebugJavaRes UP-TO-DATE
:weexplugin:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:weexplugin:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
:weexplugin:mergeDebugJniLibFolders UP-TO-DATE
:weexplugin:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:weexplugin:transformNative_libsWithSyncJniLibsForDebug UP-TO-DATE
:weexplugin:bundleDebug UP-TO-DATE
:weexplugin:compileDebugSources UP-TO-DATE
:weexplugin:assembleDebug UP-TO-DATE
:weexplugin:compileReleaseSources UP-TO-DATE
:weexplugin:assembleRelease UP-TO-DATE
:weexplugin:assemble UP-TO-DATE

BUILD SUCCESSFUL

Total time: 30.1 secs
 => Install app ...
4683 KB/s (6947043 bytes in 1.448s)
 => Running app ...`

**Comment by acathur** [comment]
Have you installed Android Studio? We need the logs in Android Studio console to find out the error locations

**Comment by TecladistaProd** [comment]
yes i have android studio, i connect my cellphone on usb and i use "weexpack run android" on windows terminal.
